### PR TITLE
fix build and release

### LINKED ISSUE #75: latest release binary giving error output
v1.1.1 is running well on my Arch Linux machine.

latest release binary is giving error output as below :  
```
align-linux: line 1: syntax error near unexpected token `newline'
align-linux: line 1: `!<arch>'
```

### PR DESCRIPTION
**Pull request by Guitarbum722**
Fixes #75

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -4,18 +4,14 @@ ARCHS="darwin linux freebsd windows"
...
-
 case "$1" in
     "release") 
         echo "Building release..."
+        # cd ${CMD_DIR}
         for arch in ${ARCHS}; do
-            GOOS=${arch} GOARCH=amd64 go build -v -o bin/align-${arch}
+            cd ${CMD_DIR}
+            GOOS=${arch} GOARCH=amd64 ${BUILD_CMD} ../../bin/align-${arch}
+            cd ../..
```
Comment (Guitarbum722) [inline build.sh:14]: @briandowns feel free to tell me I'm out to lunch with this!

Comment (briandowns) [reply build.sh:14]: Looks solid to me!

Comment (Guitarbum722) [reply build.sh:14]: Thanks for the eyes, @briandowns !
